### PR TITLE
Compile components

### PR DESCRIPTION
**Pull request by cmckni3**
build(compile): Compile components

Compile TypeScript and Angular using ngc and ts-node

### CODE REVIEW

**Comment by cmckni3** [comment]
`index.js` isn't being compiled correctly for some reason.

**Comment by sandangel** [comment]
sorry But I can't make this compile correctly, can you specify build step in package.json. I have tried with ts-node build.ts but it produce only empty index.js with some assets.

**Comment by cmckni3** [comment]
@sandangel yeah I noticed the same issue after creating the PR. There's something strange going on with `index.ts` and the `NgModule`s.

**Comment by sandangel** [comment]
Have you successfully build this module by a rollup.config.js file?

**Comment by cmckni3** [comment]
Yes with `ts-node build.ts`. I added it to the `package.json` file. For some reason, the TypeScript isn't built to JavaScript.

**Comment by sandangel** [comment]
we should separate rollup config from build script and in the build script will just have to import it. So when build script not work, we can still manually run rollup -c config.js

**Comment by sandangel** [comment]
And I think we should write this script in js, not in ts and use ts-node. Because there are some bug when directly run .ts file with ts-node

**Comment by cmckni3** [comment]
Well, you have to run the Angular compiler,`ngc` as well for the components to get built  for Angular. I like having it in `build.ts`. It's the same way the Angular Firebase team builds their library.

**Comment by cmckni3** [comment]
Hmm, never been an issue for me until now.

**Comment by cmckni3** [comment]
The interesting thing is that I can remove some of the exports and the build actually goes through but I was getting errors with `strictNullChecks` on.

**Comment by sandangel** [comment]
sure. This library is not compatible with strictNullCheck yet.

**Comment by sandangel** [comment]
Angular Firebase is really big and their build process is much more complex. And with this small build script, I think ts doesn't help much but introducing much more potential error because we don't know how ts-node internally work, how it is transpile... I really impress with build step of this library.
https://github.com/trimox/angular-mdc-web.

**Comment by cmckni3** [comment]
Only thing left to figure out is why the dropdown module won't compile. Commenting out the dropdown module allows everything to build. Error below is thrown with dropdown module included.

```
TypeError: Cannot read property 'module' of undefined
```

**Comment by sandangel** [comment]
Hello @cmckni3, Thanks for your help. I have a small build script in build-dev branch of this repo. Our priority now is have all component can be compiled to js, then we can improve build process later. I really appreciate your help. We can discuss about this build script later after we have built and published all component in js. Thanks again.

**Comment by cmckni3** [comment]
@sandangel Does the build script compile them using `ngc`? AFAIK, it the Angular compiler needs to add some extra metadata and convert some things. It uses `tsc` under the hood but has some additional processing.

**Comment by sandangel** [comment]
yes. I use a script from angular-quickstart-lib of angular/team. You can check it at build-dev branch

**Comment by sandangel** [comment]
I'm working on a build process of this library on build-dev branch. Feel free to send a PR to that branch.
There are somethings I need to improve. 
[x] Integrate testing with Jest
[ ] Add an demo page for development. I plan to use webpack.
[ ] Integrate linting
[ ] Automated test and build with CI
Any help would be appreciate.

**Comment by cmckni3** [comment]
I was going to add in a demo but I'm not sure how y'all want it structured.

I like the process from https://github.com/andyperlitch/ngx-super-table & https://github.com/webcat12345/ngx-ui-switch

**Comment by sandangel** [comment]
hi @cmckni3. Thanks for your interesting in our project. I would like to have a mono repo for our package. I also want to use gulp to automate task like material2 repo, and task file can be written in typescript. Feel free to send a PR to build-dev branch so i can review it before mdb team consider merging it to master

**Pull request closed without merging**
